name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps: 
      - name: testing
        run: |
         IMAGE_TAG=${{ github.run_number }}
         echo $IMAGE_TAGG
